language: go

env:
  - GOOS="linux" GOARCH="mipsle"
  - GOOS="linux" GOARCH="mips64"

jobs:
  include:
    - stage: Build
      script: go build -o build/speedmon_${GOOS}_${GOARCH}
    - stage: GitHub Release
      script: skip
      provider: releases
        api_key:
        file_glob: true
        file: directory/*
        skip_cleanup: true
